set(RESONANCE_GAME_SRCS
    axephrasemaker.cpp
    axingstg.cpp
    campaignstats.cpp
    catcher.cpp
    catchingstg.cpp
    controllercmd.cpp
    freqappearance.cpp
    gamemanagerimpl.cpp
    gameparams.cpp
    gamepowerupplacer.cpp
    gamerconstructcmd.cpp
    gamestats.cpp
    genericcatcher.cpp
    grooveworld.cpp
    gsperiodical.cpp
    harmony.cpp
    idablebase.cpp
    jukeboxplaylist.cpp
    levelbuilder.cpp
    levelconverter.cpp
    levelstats.cpp
    localplayer.cpp
    msgjoiner.cpp
    multicatcher.cpp
    multiscreenanim.cpp
    netplayer.cpp
    nullplayer.cpp
    phrase.cpp
    phrasedatabase.cpp
    phrasemaker.cpp
    pitchingstg.cpp
    player.cpp
    playerinfo.cpp
    playmap.cpp
    playmaplinear.cpp
    playmaprepeatring.cpp
    playmapring.cpp
    powerupcollection.cpp
    powerupcollectioni.cpp
    quantizer.cpp
    rawcontroller.cpp
    riff.cpp
    riffset.cpp
    scoretrackgraph.cpp
    screenanim.cpp
    singlepowerupcollection.cpp
    skillstats.cpp
    soloscreenanim.cpp
    tnlarena.cpp
    trackdata.cpp
    trackselector.cpp
    voxingstg.cpp)

add_library(resonance_game STATIC ${RESONANCE_GAME_SRCS})
target_link_libraries(resonance_game PRIVATE resonance_common)
