// Message and packet type identities. Every concrete message reports one of these from its
// Type() method, and the factory constructs by the same identity. The values are assigned by
// static initialisers the reconstruction has not recovered yet, so every identity starts at
// zero. The declarations live with their message classes under include/msg/.

int g_nAdvanceSectionMsgType;
int g_nAdvanceSectionToggleMsgType;
int g_nAutoCatchMsgType;
int g_nAxeButtonMsgType;
int g_nAxisFXMsgType;
int g_nAxisRegisterMsgType;
int g_nAxisXPowMsgType;
int g_nAxisYPowMsgType;
int g_nBarStatusMsgType;
int g_nBeginGameLocalMsgType;
int g_nBeginPhraseCatchMsgType;
int g_nBumpPacketType;
int g_nButtonPowMsgType;
int g_nCatchMsgType;
int g_nCatchProgressPacketType;
int g_nCaughtBarMsgType;
int g_nCaughtPhrasePacketType;
int g_nCaughtPowerbarMsgType;
int g_nChoosePowerupMsgType;
int g_nClearGemMsgType;
int g_nClearGemsMsgType;
int g_nCrippleMsgType;
int g_nCripplePacketType;
int g_nDeployedPowerupMsgType;
int g_nDisplayPointerMsgType;
int g_nDurGemMsgType;
int g_nEnableFreestyleMsgType;
int g_nEndGameMsgType;
int g_nEndMuseMsgType;
int g_nEraseMsgType;
int g_nEraseOffMsgType;
int g_nFadeGameMsgType;
int g_nFirstMuseMsgType;
int g_nFreestyleFXMsgType;
int g_nGameBeginMsgType;
int g_nGameConnectionLostMsgType;
int g_nGameManagerDoPlaybackMsgType;
int g_nGameOverMsgType;
int g_nGemMsgType;
int g_nGemPacketType;
int g_nInvalidateSeekerMsgType;
int g_nInvalidateTrackMsgType;
int g_nIsRecordingMsgType;
int g_nJamEffectMsgType;
int g_nJuiceAmountMsgType;
int g_nLobbyConnectionLostMsgType;
int g_nLoopToggleMsgType;
int g_nLoopToolMsgType;
int g_nMetFreqEndedMsgType;
int g_nMetStartNetLaunchMsgType;
int g_nMetStartPauseMsgType;
int g_nMetUnlockStagesMsgType;
int g_nMultiplierMsgType;
int g_nMultiplierStateMsgType;
int g_nNeutralizeMsgType;
int g_nNowBarMsgType;
int g_nPauseGameSystemMsgType;
int g_nPhraseCapturedMsgType;
int g_nPhraseMsgType;
int g_nPhraseMuffedMsgType;
int g_nPhrasePacketType;
int g_nPitchMsgType;
int g_nPitchRiffMsgType;
int g_nPlaybackModeMsgType;
int g_nPlaybackToggleMsgType;
int g_nPlayersTrackNeutralizedMsgType;
int g_nPointAmountMsgType;
int g_nPowerupCountMsgType;
int g_nPowerupFailedMsgType;
int g_nRawControllerMsgType;
int g_nRefreshNetMsgType;
int g_nRemixFXMsgType;
int g_nRemoteTrackSelectMsgType;
int g_nRotLeftMsgType;
int g_nRotRightMsgType;
int g_nScriptMsgType;
int g_nSectionCapturedMsgType;
int g_nSeekerMsgType;
int g_nShowEraseEffectMsgType;
int g_nStopRiffMsgType;
int g_nSusGemMsgType;
int g_nTextMsgType;
int g_nToggleGhostMsgType;
int g_nTrackSelectPacketType;
int g_nUnpauseGameSystemMsgType;
int g_nUpdateScorePacketType;
int g_nWinMsgType;

unsigned int g_dwAllNotesOffMsgType;
unsigned int g_dwMultiMuseMsgType;
unsigned int g_dwNoteMsgType;
unsigned int g_dwStdMidiMsgType;
unsigned int g_dwSustainNoteMsgType;
unsigned int g_dwTrackSelectMsgType;
unsigned int g_dwTracksOnMsgType;
