set(RESONANCE_APP_SRCS
    animrange.cpp
    application.cpp
    attachment.cpp
    cutscene.c
    durgemcurve.cpp
    durgemrowstring.cpp
    durgemstrip.cpp
    durgemtrails.cpp
    globals.cpp
    hudanalogstick.cpp
    hudanimramp.cpp
    hudbadge.cpp
    hudcountdown.cpp
    hudeffects.cpp
    hudenergy.cpp
    hudfeedback.cpp
    hudfreq.cpp
    hudgenmessage.cpp
    hudhighlight.cpp
    hudletterbox.cpp
    hudloop.cpp
    hudpanel.cpp
    hudpoints.cpp
    hudposition.cpp
    hudpowerup.cpp
    hudscore.cpp
    hudscorepulse.cpp
    hudscreenflash.cpp
    hudtcgroup.cpp
    hudtextmessage.cpp
    hudtrack.cpp
    hudtracklabel.cpp
    hudwinmessage.cpp
    hudutil.cpp
    linearramp.cpp
    longop.cpp
    mainloop.cpp
    msgqueue.cpp
    msgsink.cpp
    msgsource.cpp
    overlay.cpp
    renderer.cpp
    rendererbase.cpp
    scriptsink.cpp
    task.cpp
    tnlcatcher.cpp
    tnlpendingtrigger.cpp
    tnlpointer.cpp
    tnlsabretrail.cpp
    tnlseekerfade.cpp
    tnlutil.cpp
    tunnelcache.cpp)

add_library(resonance_app STATIC ${RESONANCE_APP_SRCS})
target_link_libraries(resonance_app PRIVATE resonance_common)
