set(RESONANCE_MET_SRCS
    albumcache.cpp
    creditsroll.cpp
    discswap.cpp
    gameoptions.cpp
    metarenasscreen.cpp
    metbuttonlist.cpp
    metconfigcontrollerscreen.cpp
    metconfiggameoptionsscreen.cpp
    metconfigoptionsbuttonsscreen.cpp
    metcreditsscreen.cpp
    metendgamegizmoscreen.cpp
    metexpansionpakscreen.cpp
    metfade.cpp
    metfreqcreatescreen.cpp
    metfreqloader.cpp
    metfreqmakerassetmanager.cpp
    metfreqmakerbuttonsscreen.cpp
    metfreqmakercanvasscreen.cpp
    metfreqmakerdirectionsscreen.cpp
    metfreqmakerinventoryscreen.cpp
    metfrontendstate.cpp
    metgameskillscreen.cpp
    metgizmopanel.cpp
    metglobalsettingssaverscreen.cpp
    metjukeboxbasescreen.cpp
    metjukeboxcustomremixesscreen.cpp
    metjukeboxeditplaylistscreen.cpp
    metjukeboxeditplaylistscreendone.cpp
    metjukeboxeditplaylistscreenlowerleft.cpp
    metjukeboxfactoryremixesscreen.cpp
    metjukeboxtopbuttonsscreen.cpp
    metkeyboardrequest.cpp
    metkeyboardscreen.cpp
    metleftgizmoscreen.cpp
    metleftgizmosmallscreen.cpp
    metloadfreqbasescreen.cpp
    metloadfreqscreen.cpp
    metloadgamescreen.cpp
    metloadnewfreqscreen.cpp
    metloadprefabscreen.cpp
    metlocpickcharscreen.cpp
    metlogoscreen.cpp
    metmainscreen.cpp
    metmcfreqdelscreen.cpp
    metmemcardloadscreen.cpp
    metmemcardtypescreen.cpp
    metmemdetectscreen.cpp
    metmemdetectstartup.cpp
    metmsgscreen.cpp
    metmultisaveremixscreen.cpp
    metmultitips1screen.cpp
    metmultitips2screen.cpp
    metmultitips3screen.cpp
    metmultitips4screen.cpp
    metmultitips5screen.cpp
    metmultitipsbasescreen.cpp
    metpausebasescreen.cpp
    metpausegamescreen.cpp
    metpausemultiremixscreen.cpp
    metpausesologamescreen.cpp
    metpausesoloremixscreen.cpp
    metpersonadata.cpp
    metpersonasaverscreen.cpp
    metremixdatascreen.cpp
    metremixdelscreen.cpp
    metremixloadscreen.cpp
    metremixmanager.cpp
    metremixsaver.cpp
    metremixtypescreen.cpp
    metrenderer.cpp
    metrightgizmoscreen.cpp
    metsaveremix.cpp
    metsaveremixscreen.cpp
    metscreen.cpp
    metsoloendremixscreen.cpp
    metsolowinscreen.cpp
    metsonglists.cpp
    metsonyscreen.cpp
    metstagefinishscreen.cpp
    mettoplogoscreen.cpp
    mettutorialscreen.cpp
    scrollinglist.cpp
    texturepairrecord.cpp)

add_library(resonance_met STATIC ${RESONANCE_MET_SRCS})
target_link_libraries(resonance_met PRIVATE resonance_common)
