set(RESONANCE_MET_SRCS
    albumcache.cpp
    gameoptions.cpp
    metarenasscreen.cpp
    metexpansionpakscreen.cpp
    metfade.cpp
    metfreqmakerdirectionsscreen.cpp
    metfrontendstate.cpp
    metglobalsettingssaverscreen.cpp
    metjukeboxbasescreen.cpp
    metjukeboxcustomremixesscreen.cpp
    metjukeboxeditplaylistscreen.cpp
    metjukeboxeditplaylistscreendone.cpp
    metjukeboxeditplaylistscreenlowerleft.cpp
    metjukeboxfactoryremixesscreen.cpp
    metjukeboxtopbuttonsscreen.cpp
    metkeyboardscreen.cpp
    metloadfreqbasescreen.cpp
    metloadfreqscreen.cpp
    metloadgamescreen.cpp
    metloadnewfreqscreen.cpp
    metloadprefabscreen.cpp
    metmcfreqdelscreen.cpp
    metmemcardloadscreen.cpp
    metmemcardtypescreen.cpp
    metmemdetectscreen.cpp
    metmemdetectstartup.cpp
    metmultisaveremixscreen.cpp
    metpersonadata.cpp
    metpersonasaverscreen.cpp
    metremixdatascreen.cpp
    metremixdelscreen.cpp
    metremixloadscreen.cpp
    metremixmanager.cpp
    metremixsaver.cpp
    metremixtypescreen.cpp
    metrenderer.cpp
    metsaveremix.cpp
    metsaveremixscreen.cpp
    metscreen.cpp
    metsoloendremixscreen.cpp
    metsolowinscreen.cpp
    metsonglists.cpp
    metstagefinishscreen.cpp
    mettoplogoscreen.cpp
    mettutorialscreen.cpp
    scrollinglist.cpp)

add_library(resonance_met STATIC ${RESONANCE_MET_SRCS})
target_link_libraries(resonance_met PRIVATE resonance_common)
