#pragma once

/**
 * Identifiers of the front-end texts in the European release's `gamestrings_*.txt` files.
 *
 * LoadMetStrings() numbers the entries of each file section from the section's base. The bases are
 * successive multiples of 100, and the memory-card section's 112 entries push the demo section to
 * 1100. Each constant is named after its key in the file, and its comment quotes the English text,
 * shortened where it is long. The North American release does not have the table. The helpers in
 * metstrings.h take an identifier in every build and use it only for the European release.
 */
enum MetStringId {
    // MetStrTrans
    kMetStrPauseGame = 100,      /*!< "Game Paused" */
    kMetStrPauseRemix = 101,     /*!< "Remix Paused" */
    kMetStrPauseTutorial = 102,  /*!< "Tutorial Paused" */
    kMetStrPauseOn = 103,        /*!< "ON" */
    kMetStrPauseOff = 104,       /*!< "OFF" */
    kMetStrLegal1 = 105,         /*!< "Frequency is a trademark of" */
    kMetStrLegal2 = 106,         /*!< "Sony Computer Entertainment America Inc." */
    kMetStrLegal3 = 107,         /*!< "Developed by Harmonix Music Systems, Inc." */
    kMetStrLegal4 = 108,         /*!< "(c) 2001 Sony Computer Entertainment America Inc." */
    kMetStrLogoStart = 109,      /*!< "Press the START button to begin" */
    kMetStrLogoback1 = 110,      /*!< "Press the" */
    kMetStrLogoback2 = 111,      /*!< "b" */
    kMetStrLogoback3 = 112,      /*!< "button to return to main menu" */
    kMetStrLoadLoading = 113,    /*!< "LOADING" */
    kMetStrLoadGame = 114,       /*!< "GAME" */
    kMetStrLoadRemix = 115,      /*!< "REMIX" */
    kMetStrLoadTut = 116,        /*!< "TUTORIAL" */
    kMetStrLoadDemo = 117,       /*!< "DEMO" */
    kMetStrLoadJukebox = 118,    /*!< "JUKEBOX" */
    kMetStrPauseResume = 119,    /*!< "Resume" */
    kMetStrPauseQuit = 120,      /*!< "Quit" */
    kMetStrPauseRestart = 121,   /*!< "Restart" */
    kMetStrPauseConfig = 122,    /*!< "Controller config" */
    kMetStrPauseSettings = 123,  /*!< "Game Settings" */
    kMetStrPauseConfirm = 124,   /*!< "Are you sure that you want to quit?" */
    kMetStrRestartConfirm = 125, /*!< "Are you sure that you want to restart?" */

    // MetStrFMak
    kMetStrPfEdit = 200,            /*!< "EDIT %s" */
    kMetStrPfCreate = 201,          /*!< "FREQMAKER" */
    kMetStrNfEnter = 202,           /*!< "ENTER NAME" */
    kMetStrNfEdit = 203,            /*!< "MODIFY BASIC FREQ" */
    kMetStrNfCreate = 204,          /*!< "FREQMAKER" */
    kMetStrLfEdit = 205,            /*!< "EDIT %s" */
    kMetStrLfCreate = 206,          /*!< "CREATE NEW FREQ" */
    kMetStrCreateFromPrefab = 207,  /*!< "MODIFY BASIC FREQ" */
    kMetStrCreateFromScratch = 208, /*!< "FREQMAKER" */
    kMetStrFqmakRandomize = 209,    /*!< "RANDOMISE" */
    kMetStrFqmakBody = 210,         /*!< "BODY" */
    kMetStrFqmakHead = 211,         /*!< "HEAD" */
    kMetStrFqmakFace = 212,         /*!< "FACE" */
    kMetStrFqmakDetails = 213,      /*!< "DETAILS" */
    kMetStrFqmakLogos = 214,        /*!< "LOGOS" */
    kMetStrFqmakEdit = 215,         /*!< "EDIT" */
    kMetStrFqmakName = 216,         /*!< "NAME" */
    kMetStrFqmakSave = 217,         /*!< "SAVE" */
    kMetStrFreqLimit = 218,         /*!< "FreQuency allows a maximum of %d FreQ campaigns..." */
    kMetStrNomemFreqLimit = 219,    /*!< "You are not allowed to create more than 8 FreQ..." */
    kMetStrFreqNoSpace = 220,       /*!< "Insufficient space on memory card (PS2)..." */
    kMetStrFmButSave = 221,         /*!< "SAVE" */
    kMetStrFmButDone = 222,         /*!< "DONE" */
    kMetStrFmButMutate = 223,       /*!< "MUTATE" */
    kMetStrFmButRandom = 224,       /*!< "RANDOMISE" */
    kMetStrFmCanvas = 225,          /*!< "FREQ CANVAS" */
    kMetStrFmDirections = 226,      /*!< "INSTRUCTIONS" */
    kMetStrFmInvColor = 227,        /*!< "COLOUR" */
    kMetStrFmInvLimit = 228,        /*!< "Inventory limited to 16 stamps" */
    kMetStrFmInvStamps = 229,       /*!< "STAMPS" */
    kMetStrFmInvHead = 230,         /*!< "HEAD" */
    kMetStrFmInvFace = 231,         /*!< "FACE" */
    kMetStrFmInvBody = 232,         /*!< "BODY" */
    kMetStrFmInvDetails = 233,      /*!< "DETAILS" */
    kMetStrFmInvLogos = 234,        /*!< "LOGOS" */
    kMetStrFmInvFreq = 235,         /*!< "FreQ" */
    kMetStrFmDefaultName = 236,     /*!< "player 1" */
    kMetStrFmConfirmSave = 237,     /*!< "%s has been edited. Do you wish to save?" */
    kMetStrTFreqMakerCreateButtons = 238, /*!< "FREQMAKER: CREATE YOUR FREQ" */
    kMetStrTFreqMakerEditButtons = 239,   /*!< "FREQMAKER: EDIT YOUR FREQ" */
    kMetStrTSelChar = 240,                /*!< "SELECT YOUR FREQ" */
    kMetStrTLoadChar = 241,               /*!< "LOAD YOUR FREQ" */
    kMetStrTCreateChar = 242,             /*!< "CREATE A FREQ" */
    kMetStrTPickChar = 243,               /*!< "SELECT A FREQ" */
    kMetStrTCreateNewChar = 244,          /*!< "CREATE NEW FREQ" */
    kMetStrTMetKbFreq = 245,              /*!< "FreQ name" */
    kMetStrHIdName = 246,                 /*!< "<FC>mn <F1> choose your freQ" */
    kMetStrHIdCreate = 247,               /*!< "create a new FreQ" */
    kMetStrHIdEdit = 248,                 /*!< "edit your image or info" */
    kMetStrHCidName = 249,                /*!< "<FC>mn <F1> choose from pre-fab freQs" */
    kMetStrHCidSave = 250,                /*!< "save this FreQ" */
    kMetStrHCidAccept = 251,              /*!< "proceed with this FreQ" */
    kMetStrHCidEdit = 252,                /*!< "edit your FreQ" */
    kMetStrHCreateFromPrefab = 253,       /*!< "create new freQ from basic freQs" */
    kMetStrHCreateFromScratch = 254,      /*!< "create new freQ from scratch" */
    kMetStrHNameNewFreqTicker = 255,      /*!< "Hit Enter to Save freQ" */
    kMetStrHPCustID = 256,                /*!< "design your freQ" */
    kMetStrHPInfo = 257,                  /*!< Empty. */
    kMetStrHPViewp = 258,                 /*!< "view your FreQ profile" */
    kMetStrHPSave = 259,                  /*!< "save your FreQ" */
    kMetStrHFqmakRandomize = 260,         /*!< "<FC> d <F1> generate a random freq" */
    kMetStrHFqmakMutate = 261,            /*!< "<FC> d <F1> mutate your freq" */
    kMetStrHFqmakBody = 262,              /*!< "<FC> d <F1> select a body stamp" */
    kMetStrHFqmakHead = 263,              /*!< "<FC> d <F1> select a head stamp" */
    kMetStrHFqmakFace = 264,              /*!< "<FC> d <F1> select a face stamp" */
    kMetStrHFqmakDetails = 265,           /*!< "<FC> d <F1> select a detail stamp" */
    kMetStrHFqmakLogos = 266,             /*!< "<FC> d <F1> select a logo stamp" */
    kMetStrHFqmakEdit = 267,              /*!< "<FC> d <F1> edit your freq" */
    kMetStrHFqmakName = 268,              /*!< "<FC> d <F1> name your freq" */
    kMetStrHFqmakSave = 269,              /*!< "<FC> d <F1> save your freq" */
    kMetStrHFqmakDone = 270,              /*!< "<FC> d <F1> proceed" */
    kMetStrHFqmakEditingMode = 271,       /*!< "right analog stick to position stamp" */
    kMetStrHFqmakPositioningMode = 272,   /*!< "right analog stick to position stamp" */
    kMetStrHFqmakChoosingMode = 273,      /*!< "<FC> k l m n <F1> to select a stamp" */
    kMetStrHFqmakFreqfull = 274,          /*!< "freQ has maximum number of stamps" */
    kMetStrHFqmakColoringMode = 275,      /*!< "right analog stick to select colour" */
    kMetStrHMetFmNameFreq = 276,          /*!< "name your freQ" */
    kMetStrHFreqMakerSaveButton = 277,    /*!< "<FC> d <F2>SAVE <FC> b <F2>BACK" */
    kMetStrHPUsername = 278,              /*!< "type your freQ name. <FC>c <F1> keyboard." */

    // MetStrFMakDir
    kMetStrFmEditingMode1 = 300,     /*!< "switch to colour" */
    kMetStrFmEditingMode2 = 301,     /*!< "panel" */
    kMetStrFmEditingMode3 = 302,     /*!< "bring stamp to front" */
    kMetStrFmEditingMode4 = 303,     /*!< "push stamp to back" */
    kMetStrFmEditingMode5 = 304,     /*!< "flip stamp" */
    kMetStrFmEditingMode6 = 305,     /*!< "reset stamp" */
    kMetStrFmEditingMode7 = 306,     /*!< "delete stamp" */
    kMetStrFmPositioningMode1 = 307, /*!< "switch to colour" */
    kMetStrFmPositioningMode2 = 308, /*!< "panel" */
    kMetStrFmPositioningMode3 = 309, /*!< "bring stamp to front" */
    kMetStrFmPositioningMode4 = 310, /*!< "push stamp to back" */
    kMetStrFmPositioningMode5 = 311, /*!< "flip stamp" */
    kMetStrFmColoringMode1 = 312,    /*!< "switch to freq" */
    kMetStrFmColoringMode2 = 313,    /*!< "canvas" */
    kMetStrFmChoosingMode1 = 314,    /*!< "select stamp to" */
    kMetStrFmChoosingMode2 = 315,    /*!< "edit" */
    kMetStrFmFreqFullMode1 = 316,    /*!< "your freQ has the" */
    kMetStrFmFreqFullMode2 = 317,    /*!< "maximum number" */
    kMetStrFmFreqFullMode3 = 318,    /*!< "of stamps" */
    kMetStrFmEditButton1 = 319,      /*!< "edit the colour and" */
    kMetStrFmEditButton2 = 320,      /*!< "position of your" */
    kMetStrFmEditButton3 = 321,      /*!< "freq stamps" */
    kMetStrFmBodyButton1 = 322,      /*!< "choose from 24" */
    kMetStrFmBodyButton2 = 323,      /*!< "body stamps" */
    kMetStrFmHeadButton1 = 324,      /*!< "choose from 24" */
    kMetStrFmHeadButton2 = 325,      /*!< "head stamps" */
    kMetStrFmFaceButton1 = 326,      /*!< "choose from 24" */
    kMetStrFmFaceButton2 = 327,      /*!< "face stamps" */
    kMetStrFmDetailsButton1 = 328,   /*!< "choose from 24" */
    kMetStrFmDetailsButton2 = 329,   /*!< "details stamps" */
    kMetStrFmLogosButton1 = 330,     /*!< "choose from 24" */
    kMetStrFmLogosButton2 = 331,     /*!< "logo stamps" */
    kMetStrFmMutateButton1 = 332,    /*!< "mutate your freq" */
    kMetStrFmMutateButton2 = 333,    /*!< "stamps" */
    kMetStrFmRandomizeButton1 = 334, /*!< "randomise your" */
    kMetStrFmRandomizeButton2 = 335, /*!< "entire freq" */
    kMetStrFmNameButton1 = 336,      /*!< "use the keyboard" */
    kMetStrFmNameButton2 = 337,      /*!< "to name your freq" */
    kMetStrFmSaveButton1 = 338,      /*!< "save to MEMORY" */
    kMetStrFmSaveButton2 = 339,      /*!< "CARD slot %s" */
    kMetStrFmDoneButton1 = 340,      /*!< "Accept changes" */
    kMetStrFmDoneButton2 = 341,      /*!< "and proceed" */

    // MetStrOpt
    kMetStrNobGameSetup = 400,                  /*!< "GAME SETTINGS" */
    kMetStrNobControllerSetup = 401,            /*!< "PLAYER SETUP" */
    kMetStrNobMemCardSetup = 402,               /*!< "DATA MANAGER" */
    kMetStrNobDiskChange = 403,                 /*!< "DISC CHANGE" */
    kMetStrNobCredits = 404,                    /*!< "CREDITS" */
    kMetStrConfigControllerPlayer = 405,        /*!< "PLAYER" */
    kMetStrConfigControllerSetup = 406,         /*!< "SETUP" */
    kMetStrControllerConfigLeftNote1 = 407,     /*!< "Left Note" */
    kMetStrControllerConfigLeftNote2 = 408,     /*!< "Left Note" */
    kMetStrControllerConfigCenterNote1 = 409,   /*!< "Centre Note" */
    kMetStrControllerConfigCenterNote2 = 410,   /*!< "Centre Note" */
    kMetStrControllerConfigRightNote1 = 411,    /*!< "Right Note" */
    kMetStrControllerConfigRightNote2 = 412,    /*!< "Right Note" */
    kMetStrControllerConfigEraseAndPower = 413, /*!< "Erase & Powerup" */
    kMetStrControllerConfigExpression = 414,    /*!< "Expression" */
    kMetStrControllerConfigRemixFx = 415,       /*!< "Remix Fx" */
    kMetStrControllerConfigRotate = 416,        /*!< "Rotate" */
    kMetStrControllerConfigAdvance = 417,       /*!< "Advance" */
    kMetStrControllerConfigLoop = 418,          /*!< "Loop Mode" */
    kMetStrControllerConfigExit = 419,          /*!< "Exit" */
    kMetStrControllerConfigPlayback = 420,      /*!< "Playback" */
    kMetStrControllerConfigInstruct1 = 421,     /*!< "set control for selected action" */
    kMetStrControllerConfigInstruct2 = 422,     /*!< "restore default configuration" */
    kMetStrControllerConfigWarn = 423,       /*!< "You must choose a button for every selection." */
    kMetStrPsxActionsPan = 424,              /*!< "ACTIONS" */
    kMetStrPsxDiagramPan = 425,              /*!< "CONTROLLER" */
    kMetStrPsxLeftAnalog = 426,              /*!< "left analog stick" */
    kMetStrPsxRightAnalog = 427,             /*!< "right analog stick" */
    kMetStrGsStereo = 428,                   /*!< "STEREO" */
    kMetStrGsMono = 429,                     /*!< "MONO" */
    kMetStrGsFfOn = 430,                     /*!< "ON" */
    kMetStrGsFfOff = 431,                    /*!< "OFF" */
    kMetStrPangameAudio = 432,               /*!< "Mono / Stereo" */
    kMetStrPangameBeatAssist = 433,          /*!< "Optical Out" */
    kMetStrPangameForceFeedback = 434,       /*!< "Force Feedback" */
    kMetStrPangameAudioLbl = 435,            /*!< "AUDIO" */
    kMetStrPangameForceLbl = 436,            /*!< "VIBRATION FUNCTION" */
    kMetStrPangameBeatLbl = 437,             /*!< "OPTICAL OUT" */
    kMetStrExpansionPrepare = 438,           /*!< "Opening CD tray for DISC exchange..." */
    kMetStrExpansionCheck = 439,             /*!< "Please remove the current FreQuency DISC..." */
    kMetStrExpansionRetry = 440,             /*!< "Attempt to load DISC failed..." */
    kMetStrExpansionLoad = 441,              /*!< "Scanning DISC..." */
    kMetStrExpansionDone1 = 442,             /*!< "FreQuency DISC" */
    kMetStrExpansionDone2 = 443,             /*!< "has been loaded." */
    kMetStrKbMacroF1 = 444,                  /*!< Empty. */
    kMetStrKbMacroF2 = 445,                  /*!< Empty. */
    kMetStrKbMacroF3 = 446,                  /*!< Empty. */
    kMetStrKbMacroF4 = 447,                  /*!< Empty. */
    kMetStrKbMacroF5 = 448,                  /*!< Empty. */
    kMetStrKbMacroF6 = 449,                  /*!< Empty. */
    kMetStrKbMacroF7 = 450,                  /*!< Empty. */
    kMetStrKbMacroF8 = 451,                  /*!< Empty. */
    kMetStrKbMacroF9 = 452,                  /*!< Empty. */
    kMetStrKbMacroF10 = 453,                 /*!< Empty. */
    kMetStrKbMacroF11 = 454,                 /*!< Empty. */
    kMetStrKbMacroF12 = 455,                 /*!< Empty. */
    kMetStrKbTab = 456,                      /*!< "TAB" */
    kMetStrKbCaps = 457,                     /*!< "CAPS" */
    kMetStrKbShift = 458,                    /*!< "SHIFT" */
    kMetStrKbBack = 459,                     /*!< "BACK" */
    kMetStrKbEnter = 460,                    /*!< "ENTER" */
    kMetStrKbDel = 461,                      /*!< "DEL" */
    kMetStrKbSpace = 462,                    /*!< "SPACE" */
    kMetStrTConfigOptionButtons = 463,       /*!< "CONFIGURATION OPTIONS" */
    kMetStrTCustomMacroScreen = 464,         /*!< "CUSTOM MACROS" */
    kMetStrTConfigControllerOptions = 465,   /*!< "CONFIGURATION" */
    kMetStrTPangameOptions = 466,            /*!< "GAME SETTINGS" */
    kMetStrHNobGameSetup = 467,              /*!< "change your settings" */
    kMetStrHNobControllerSetup = 468,        /*!< "customize controller configuration" */
    kMetStrHNobMemCardSetup = 469,           /*!< "load, delete & copy freQs and remixes" */
    kMetStrHNobDiskChange = 470,             /*!< "expansion pack access" */
    kMetStrHNobCredits = 471,                /*!< "the FreQ freQs..." */
    kMetStrHControllerConfigLeftNote1 = 472, /*!< "<FC> m n <F1> primary left note button" */
    kMetStrHControllerConfigLeftNote2 = 473, /*!< "<FC> m n <F1> secondary left note button" */
    kMetStrHControllerConfigCenterNote1 = 474, /*!< "<FC> m n <F1> primary center note button" */
    kMetStrHControllerConfigCenterNote2 = 475, /*!< "<FC> m n <F1> secondary center note button" */
    kMetStrHControllerConfigRightNote1 = 476,  /*!< "<FC> m n <F1> primary right note button" */
    kMetStrHControllerConfigRightNote2 = 477,  /*!< "<FC> m n <F1> secondary right note button" */
    kMetStrHControllerConfigEraseAndPower = 478, /*!< "<FC> m n <F1> erase & powerup button" */
    kMetStrHControllerConfigExpression = 479,    /*!< "<FC> m n <F1> expression button" */
    kMetStrHControllerConfigRemixFx = 480,       /*!< "<FC> m n <F1> remix fx button" */
    kMetStrHPangameAudio = 481,                  /*!< "<FC> m n <F1> select mono / stereo" */
    kMetStrHPangameBeatAssist = 482,             /*!< "<FC> m n <F1> audio clues" */
    kMetStrHPangameForceFeedback = 483,          /*!< "<FC> m n <F1> controller vibration" */
    kMetStrHPangameTabText = 484,                /*!< "<FC> d <F2> SAVE <FC> b <F2> BACK" */
    kMetStrHPangameTabTextDEMO = 485,            /*!< "<FC> b <F2> BACK" */
    kMetStrHCcSaveBack = 486,                    /*!< "<FC> d <F2>SAVE <FC> b <F2>BACK" */
    kMetStrHMetKeyboardMacroTooLarge = 487,      /*!< "macro too large for the space allowed" */

    // MetStrSoloMulti
    kMetStrTut = 500,              /*!< "TUTORIALS" */
    kMetStrSolo = 501,             /*!< "SOLO" */
    kMetStrMulti = 502,            /*!< "MULTI" */
    kMetStrOpt = 503,              /*!< "OPTIONS" */
    kMetStrTutG = 504,             /*!< "GAME MODE" */
    kMetStrTutR = 505,             /*!< "REMIX MODE" */
    kMetStrMsGame = 506,           /*!< "GAME" */
    kMetStrMsJam = 507,            /*!< "REMIX" */
    kMetStrMsNewjam = 508,         /*!< "NEW REMIX" */
    kMetStrMsLoadjam = 509,        /*!< "LOAD REMIX" */
    kMetStrMsJukebox = 510,        /*!< "JUKEBOX" */
    kMetStrRlSaved = 511,          /*!< "SAVED" */
    kMetStrRlFactory = 512,        /*!< "FACTORY" */
    kMetStrMsEasy = 513,           /*!< "NORMAL" */
    kMetStrMsNormal = 514,         /*!< "ADVANCED" */
    kMetStrMsExpert = 515,         /*!< "EXPERT" */
    kMetStrRemixUnavailDisc = 516, /*!< "NOT PLAYABLE FROM CURRENT DISC" */
    kMetStrStage1 = 517,           /*!< "STAGE 1" */
    kMetStrStage2 = 518,           /*!< "STAGE 2" */
    kMetStrStage3 = 519,           /*!< "STAGE 3" */
    kMetStrStage4 = 520,           /*!< "STAGE 4" */
    kMetStrStage5 = 521,           /*!< "STAGE 5" */
    kMetStrHighscore = 522,        /*!< "High Score: %d" */
    kMetStrExit = 523,             /*!< "EXIT" */
    kMetStrStage = 524,            /*!< "STAGE" */
    kMetStrSsCustom = 525,         /*!< "CUSTOM" */
    kMetStrStageScore = 526,       /*!< "Stage Score :" */
    kMetStrStageBeat = 527,        /*!< "Try to Beat :" */
    kMetStrBonusMsg = 528,         /*!< "Beat all %d songs with a total stage score..." */
    kMetStrStage4easywarn = 529,   /*!< "AVAILABLE IN ADVANCED AND EXPERT MODE" */
    kMetStrStage5easywarn = 530,   /*!< "AVAILABLE IN EXPERT MODE ONLY" */
    kMetStrCustomWarning = 531,    /*!< "PRESS X TO LOAD CUSTOM REMIXES AS GAME SONGS" */
    kMetStrArena1 = 532,           /*!< "ARENA 1" */
    kMetStrArena2 = 533,           /*!< "ARENA 2" */
    kMetStrArena3 = 534,           /*!< "ARENA 3" */
    kMetStrArena4 = 535,           /*!< "ARENA 4" */
    kMetStrArena5 = 536,           /*!< "ARENA 5" */
    kMetStrArena6 = 537,           /*!< "ARENA 6" */
    kMetStrArena7 = 538,           /*!< "ARENA 7" */
    kMetStrArena8 = 539,           /*!< "ARENA 8" */
    kMetStrArenaNone = 540,        /*!< "NO ARENA" */
    kMetStrTMain = 541,            /*!< "MAIN SCREEN" */
    kMetStrTSolo = 542,            /*!< "SOLO" */
    kMetStrTMulti = 543,           /*!< "MULTI" */
    kMetStrTTutorial = 544,        /*!< "SELECT TUTORIAL" */
    kMetStrTMode = 545,            /*!< ": SELECT MODE" */
    kMetStrTSkill = 546,           /*!< "%s GAME: SELECT SKILL" */
    kMetStrTRemixType = 547,       /*!< ": SELECT REMIX" */
    kMetStrTStages = 548,          /*!< ": SELECT SONG" */
    kMetStrTGame = 549,            /*!< "GAME" */
    kMetStrTRemix = 550,           /*!< "REMIX" */
    kMetStrTArenas = 551,          /*!< ": SELECT ARENA" */
    kMetStrHMsTut = 552,           /*!< "learn to play" */
    kMetStrHMsSolo = 553,          /*!< "you vs. frequency" */
    kMetStrHMsMulti = 554,         /*!< "you vs. your friends" */
    kMetStrHMsOpt = 555,           /*!< "adjust your settings" */
    kMetStrHTutG = 556,            /*!< "learn to play game mode" */
    kMetStrHTutR = 557,            /*!< "learn to play remix mode" */
    kMetStrHSmsGame = 558,         /*!< "beat the game" */
    kMetStrHSmsJam = 559,          /*!< "create custom remixes" */
    kMetStrHMmsGame = 560,         /*!< "compete against your friends" */
    kMetStrHMmsJam = 561,          /*!< "create a remix with your friends" */
    kMetStrHSmgsEasy = 562,        /*!< "beat 16 beginner songs" */
    kMetStrHSmgsNormal = 563,      /*!< "beat 21 challenging songs" */
    kMetStrHSmgsExpert = 564,      /*!< "beat 26 mind-numbing songs" */
    kMetStrHMgsEasy = 565,         /*!< "16 beginner songs" */
    kMetStrHMgsNormal = 566,       /*!< "21 challenging songs" */
    kMetStrHMgsExpert = 567,       /*!< "26 mind-numbing songs" */
    kMetStrHSmrtNew = 568,         /*!< "create custom remix" */
    kMetStrHSmrtLoad = 569,        /*!< "load saved or factory remixes" */
    kMetStrHSmrtJukebox = 570,     /*!< "make a remix mega-mix" */
    kMetStrHMemLoadRemix = 571,    /*!< "<FC>kl <F1> select remix to load" */
    kMetStrHMemLoadCustom = 572,   /*!< "<FC>kl <F1> select remix to load custom song" */
    kMetStrHLevels = 573,          /*!< "<FC>kl <F1> next stage <FC>mn <F1> next song" */
    kMetStrHArenas = 574,          /*!< "<FC>kl <F1> next arena" */
    kMetStrHMetSaveRemixScreenTickerTape = 575, /*!< "name your remix" */
    kMetStrHKbRemixSave = 576,                  /*!< "Remix name" */
    kMetStrHStandardTitle = 577,                /*!< "<FC> d <F2>ACCEPT <FC> b <F2>BACK" */
    kMetStrHNoBackTitle = 578,                  /*!< "<FC> d <F2>ACCEPT" */
    kMetStrHOnlyBackTitle = 579,                /*!< "<FC> b <F2>BACK" */
    kMetStrHKeyboardClearTicker = 580,          /*!< Empty. */
    kMetStrHMetKeyboardTextTooWide = 581,       /*!< "text limit reached" */
    kMetStrHMetKbMacroError = 582,              /*!< "Not enough room to insert Macro." */

    // MetStrJuke
    kMetStrJbbSavedRemixes = 600,                 /*!< "SAVED REMIXES" */
    kMetStrJbbFactoryRemixes = 601,               /*!< "FACTORY REMIXES" */
    kMetStrJbbEditPlaylist = 602,                 /*!< "EDIT PLAYLIST" */
    kMetStrJbbDone = 603,                         /*!< "DONE" */
    kMetStrJbedInstruct = 604,                    /*!< "INSTRUCTIONS" */
    kMetStrJbedSort = 605,                        /*!< "sort UP/DOWN" */
    kMetStrJbedDel = 606,                         /*!< "delete entry" */
    kMetStrJbedClear = 607,                       /*!< "clear list" */
    kMetStrJbPlaylist = 608,                      /*!< "My Playlist" */
    kMetStrJbdRandom = 609,                       /*!< "PLAY RANDOM" */
    kMetStrJbdOrder = 610,                        /*!< "PLAY IN ORDER" */
    kMetStrJbdSave = 611,                         /*!< "SAVE PLAYLIST" */
    kMetStrTMetJukeboxTitle = 612,                /*!< "JUKEBOX" */
    kMetStrTMetJukeboxCreateTitle = 613,          /*!< "JUKEBOX: CREATE PLAYLIST" */
    kMetStrTMetJukeboxEditTitle = 614,            /*!< "JUKEBOX: EDIT PLAYLIST" */
    kMetStrTMetJukeboxPlayTitle = 615,            /*!< "JUKEBOX: PLAY" */
    kMetStrHMetJukeboxBaseScreenHelpTab = 616,    /*!< "<FC>d<F2> ADD <FC>b<F2> BACK" */
    kMetStrHMetJukeboxBaseScreenTickerTape = 617, /*!< "<FC>d<F1> add remix to my playlist" */
    kMetStrHMetJukeboxEditScreenHelpTab = 618,    /*!< "<FC>d<F2> DELETE <FC>b<F2> BACK" */
    kMetStrHMetJukeboxEditScreenTickerTape = 619, /*!< "<FC>d<F1> remove remix from my playlist" */
    kMetStrHMetJukeboxDoneScreenTabPlay = 620,    /*!< "<FC>d<F2> LOAD <FC>b<F2> BACK" */
    kMetStrHMetJukeboxDoneScreenTickerPlay = 621, /*!< "<FC>d<F1> play my playlist" */
    kMetStrHMetJukeboxDoneScreenTabSave = 622,    /*!< "<FC>d<F2> SAVE <FC>b<F2> BACK" */
    kMetStrHMetJukeboxDoneScreenTickerSave = 623, /*!< "<FC>d<F1> save my playlist" */
    kMetStrHMetJukeboxBaseScreenErrorTickerTape = 624, /*!< "playlist limit reached" */
    kMetStrHMetJukeboxBaseScreenErrorTab = 625,        /*!< "<FC>b<F2> BACK" */

    // MetStrMulti
    kMetStrLoc2p = 700,         /*!< "2 PLAYERS" */
    kMetStrLoc3p = 701,         /*!< "3 PLAYERS" */
    kMetStrLoc4p = 702,         /*!< "4 PLAYERS" */
    kMetStrMultiTips = 703,     /*!< "MULTI TIPS" */
    kMetStrTpPanel = 704,       /*!< "TIPS" */
    kMetStrTpActivator1 = 705,  /*!< "PLAYER 1 ACTIVATOR" */
    kMetStrTpActivator2 = 706,  /*!< "PLAYER 2 ACTIVATOR" */
    kMetStrTpScore1 = 707,      /*!< "PLAYER 1 SCORE" */
    kMetStrTpScore2 = 708,      /*!< "PLAYER 2 SCORE" */
    kMetStrTp1Title = 709,      /*!< "HOW TO PLAY MULTIPLAYER:" */
    kMetStrTp1Help = 710,       /*!< "In multiplayer mode, you can catch only one bar..." */
    kMetStrTp2Title1 = 711,     /*!< "SCORING:" */
    kMetStrTp2Help1 = 712,      /*!< "Complex note patterns will give you more points..." */
    kMetStrTp2Title2 = 713,     /*!< "HOT STREAK BONUS:" */
    kMetStrTp2Help2 = 714,      /*!< "Catch multiple bars in a row for an added bonus!" */
    kMetStrTp3Panel = 715,      /*!< "POWERUPS" */
    kMetStrTp3Notes = 716,      /*!< "POWERUP NOTES" */
    kMetStrTp3Inventory = 717,  /*!< "INVENTORY" */
    kMetStrTp3Title1 = 718,     /*!< "HOW TO CATCH POWERUPS:" */
    kMetStrTp3Help1 = 719,      /*!< "Capture all of the special powerup notes in a bar..." */
    kMetStrTp3Title2 = 720,     /*!< "HOW TO USE POWERUPS:" */
    kMetStrTp3Help2 = 721,      /*!< "Press the X button to deploy a powerup..." */
    kMetStrTp4HudLabel = 722,   /*!< "HUD" */
    kMetStrTp4NoteLabel = 723,  /*!< "NOTE" */
    kMetStrTp4DescLabel = 724,  /*!< "POWERUP DESCRIPTION" */
    kMetStrTp4Title1 = 725,     /*!< "AUTOCATCHER:" */
    kMetStrTp4Help1 = 726,      /*!< "Deploy on free notes to catch them automatically." */
    kMetStrTp4Title2 = 727,     /*!< "FREESTYLER:" */
    kMetStrTp4Help2 = 728,      /*!< "Deploy on an Axe track or a Scratch track..." */
    kMetStrTp4Title3 = 729,     /*!< "CRIPPLER:" */
    kMetStrTp4Help3 = 730,      /*!< "Deploy on another player's activator..." */
    kMetStrTp4Title4 = 731,     /*!< "NEUTRALIZER:" */
    kMetStrTp4Help4 = 732,      /*!< "Deploy on your opponent's captured track..." */
    kMetStrTp4Title5 = 733,     /*!< "BUMPER:" */
    kMetStrTp4Help5 = 734,      /*!< "Deploy on another player's activator to bump them..." */
    kMetStrTp5Panel = 735,      /*!< "COLOURS" */
    kMetStrTp5Title = 736,      /*!< "PLAYER COLOURS:" */
    kMetStrTp5Help = 737,       /*!< "Each player's activator, notes, panels, name..." */
    kMetStrTMNumP = 738,        /*!< "MULTI: SELECT NUMBER" */
    kMetStrTMpChar = 739,       /*!< "MULTI: SELECT YOUR FREQ" */
    kMetStrTMultiTips = 740,    /*!< "MULTIPLAYER TIPS" */
    kMetStrHLoc2p = 741,        /*!< "select number of players" */
    kMetStrHLoc3p = 742,        /*!< "select number of players" */
    kMetStrHLoc4p = 743,        /*!< "select number of players" */
    kMetStrHMultiTips = 744,    /*!< "learn to play multi mode" */
    kMetStrHMultiTipHelp = 745, /*!< "<FC> a <F1> exit multiplayer tips" */
    kMetStrHLocPc = 746,        /*!< "<FC> mn <F1> choose your freq" */
    kMetStrHMultiTipsTab = 747, /*!< "<FC> b <F2>BACK <FC> d <F2>NEXT" */

    // MetStrEndGame
    kMetStrEndGameCongrats = 800,       /*!< "CONGRATULATIONS" */
    kMetStrEndGameHighScore = 801,      /*!< "New High Score!" */
    kMetStrEndGameArenaComplete = 802,  /*!< "%s Arena unlocked." */
    kMetStrStageScoreBeat = 803,        /*!< "Bonus song unlocked." */
    kMetStrEndGameStage = 804,          /*!< "Stage %d unlocked." */
    kMetStrEndGameLastStage = 805,      /*!< "Beat all bonus songs to win at %s." */
    kMetStrEndGameEasyNormal = 806,     /*!< "To unlock more songs, play at %s skill level." */
    kMetStrEndGameSecret = 807,         /*!< "Secret song unlocked." */
    kMetStrEndGameSuperSecret = 808,    /*!< "Super secret song unlocked." */
    kMetStrEndGameEndSuperSecret = 809, /*!< "You beat the Super Secret Song!..." */
    kMetStrEgsPanelLabel = 810,         /*!< "PLAYER STATS" */
    kMetStrEgsScoreLabel = 811,         /*!< "SCORE:" */
    kMetStrEgsSongLabel = 812,          /*!< "SONG:" */
    kMetStrEgsSkillLabel = 813,         /*!< "SKILL:" */
    kMetStrEgsComplete1Label = 814,     /*!< "% of song" */
    kMetStrEgsComplete2Label = 815,     /*!< "complete:" */
    kMetStrEgsPhrase1Label = 816,       /*!< "phrase capture" */
    kMetStrEgsPhrase2Label = 817,       /*!< "accuracy:" */
    kMetStrEgsHottestLabel = 818,       /*!< "hottest streak:" */
    kMetStrEgsPerfect = 819,            /*!< "PERFECT!" */
    kMetStrRemixPlayer = 820,           /*!< "PLAYER" */
    kMetStrRemixPanelLabel = 821,       /*!< "REMIX DATA" */
    kMetStrMultiSaveRemixLabel = 822,   /*!< "REMIX PLAYERS" */
    kMetStrMultiSaveInstruct = 823,     /*!< "Would you like to save?" */
    kMetStrEgmGameLabel = 824,          /*!< "GAME DATA" */
    kMetStrEgmRemixLabel = 825,         /*!< "REMIX DATA" */
    kMetStrEgmGamePlayerLabel = 826,    /*!< "SCORES" */
    kMetStrEgmRemixPlayerLabel = 827,   /*!< "PLAYERS" */
    kMetStrEgslAgain = 828,             /*!< "PLAY AGAIN" */
    kMetStrEgslLevels = 829,            /*!< "EXIT" */
    kMetStrEgswContinue = 830,          /*!< "CONTINUE" */
    kMetStrEgswExit = 831,              /*!< "QUIT" */
    kMetStrEgswRestart = 832,           /*!< "PLAY AGAIN" */
    kMetStrEgsrContinue = 833,          /*!< "CONTINUE" */
    kMetStrEgmgAgain = 834,             /*!< "PLAY AGAIN" */
    kMetStrEgmgNew = 835,               /*!< "NEW GAME" */
    kMetStrEgmrContinue = 836,          /*!< "CONTINUE" */
    kMetStrEgngContinue = 837,          /*!< "CONTINUE" */
    kMetStrStfContinue = 838,           /*!< "CONTINUE" */
    kMetStrStfExit = 839,               /*!< "EXIT" */
    kMetStrSaveRemixTitle = 840,        /*!< "REMIX TITLE" */
    kMetStrTSoloLose = 841,             /*!< "SOLO GAME: YOU LOSE" */
    kMetStrTSoloWin = 842,              /*!< "SOLO GAME: YOU WIN" */
    kMetStrTSoloRemixOver = 843,        /*!< "END SOLO REMIX" */
    kMetStrTMultiGameOver = 844,        /*!< "MULTIPLAYER GAME OVER" */
    kMetStrTMultiRemixOver = 845,       /*!< "END MULTIPLAYER REMIX" */
    kMetStrHEgslAgain = 846,            /*!< "play this song again" */
    kMetStrHEgslLevels = 847,           /*!< "return to song select screen" */
    kMetStrHEgswContinue = 848,         /*!< "return to song select screen" */
    kMetStrHEgswExit = 849,             /*!< "return to main menu" */
    kMetStrHEgswRestart = 850,          /*!< "play this song again" */
    kMetStrHEgmgAgain = 851,            /*!< "play this song again" */
    kMetStrHEgmgNew = 852,              /*!< "return to song select screen" */
    kMetStrHRemixSave = 853,            /*!< "<FC> c <F1> to bring up keyboard" */
    kMetStrHRemixSaveOptions = 854,     /*!< "<FC> d <F2>SAVE <FC> a <F2>DISCARD" */

    // MetStrMemCard
    kMetStrMemCardSelect = 900,      /*!< "SELECT" */
    kMetStrMcSelNone = 901,          /*!< "no memory cards (PS2) available" */
    kMetStrMcSelCard = 902,          /*!< "select MEMORY CARD slot" */
    kMetStrMcSpaceAvail = 903,       /*!< "%i KB available" */
    kMetStrMcSlot1 = 904,            /*!< "memory" */
    kMetStrMcSlot2 = 905,            /*!< "card slot" */
    kMetStrMemCardLoadWarning = 906, /*!< "If you proceed the current campaign data will be..." */
    kMetStrMemDetect = 907,      /*!< "Checking for memory card (PS2) in MEMORY CARD slot 1..." */
    kMetStrMemDetect12 = 908,    /*!< "Checking for memory cards (PS2) in slots 1 and 2..." */
    kMetStrMemDetectMulti = 909, /*!< "Checking for memory cards (PS2) in slots (1-%d)..." */
    kMetStrMemCheck = 910,       /*!< "No memory card (PS2) detected in MEMORY CARD slot 1..." */
    kMetStrMemCheck12 = 911,     /*!< "No memory cards (PS2) detected in slots 1 or 2." */
    kMetStrMemLoad = 912,        /*!< "Loading data from memory card (PS2)..." */
    kMetStrMemAutosave = 913,    /*!< "FreQuency uses an auto save system..." */
    kMetStrMemNospace = 914,     /*!< "Insufficient space on memory card (PS2)..." */
    kMetStrMemNospaceForCampaign = 915, /*!< "Insufficient space on memory card (PS2)..." */
    kMetStrMemNeedsSpace = 916,         /*!< "There is insufficient space on the memory card..." */
    kMetStrMemError = 917,         /*!< "FreQuency requires a formatted memory card (PS2)..." */
    kMetStrMemDetectSpecial = 918, /*!< "No memory card (PS2) detected in slot %s..." */
    kMetStrMemFormatCheck = 919,   /*!< "The memory card (PS2) in slot %s is not formatted..." */
    kMetStrMemFormatGo = 920,      /*!< "The memory card (PS2) in slot %s is being formatted..." */
    kMetStrFormatSuccess = 921,    /*!< "The memory card (PS2) in slot %s has been formatted." */
    kMetStrFormatAlready = 922,    /*!< "The memory card (PS2) in slot %s was not formatted..." */
    kMetStrFormatFail = 923,       /*!< "Formatting failed." */
    kMetStrSaveFail = 924,         /*!< "Save failed." */
    kMetStrSaveAborted = 925,      /*!< "Save aborted." */
    kMetStrCopyFail = 926,         /*!< "Copying failed." */
    kMetStrLoadFail = 927,         /*!< "Loading failed." */
    kMetStrLoadFailJukebox = 928,  /*!< "Load failed - Required remixes are not on this card." */
    kMetStrDelFail = 929,          /*!< "Delete failed." */
    kMetStrDelFailNocard = 930,    /*!< "Delete failed. No memory card (PS2) was detected..." */
    kMetStrDelFailNotfound = 931,  /*!< "Delete failed. %s not found on the memory card..." */
    kMetStrMemSave = 932,          /*!< "Saving data to memory card (PS2)..." */
    kMetStrSaveFailNocard = 933,   /*!< "Save failed. No memory card (PS2) was detected..." */
    kMetStrSaveFailNospace = 934,  /*!< "Save failed. Insufficient space on memory card..." */
    kMetStrSaveFailFormat = 935,   /*!< "Save failed. The memory card (PS2) is not formatted..." */
    kMetStrSaveFailGeneral = 936,  /*!< "Save failed." */
    kMetStrNoSaveWarn = 937,       /*!< "FreQuency requires a memory card (PS2)..." */
    kMetStrFreqDelOk = 938,        /*!< "Are you sure you want to delete your FreQ campaign?" */
    kMetStrFreqMidDel1 = 939,      /*!< "Deleting your FreQ campaign from memory card (PS2)..." */
    kMetStrFreqMidDel2 = 940,      /*!< ". Do not remove your memory card (PS2)." */
    kMetStrFreqCopyOk = 941,       /*!< "Do you want to copy this freQ to the memory card..." */
    kMetStrFreqReplace = 942,      /*!< "There is a FreQ with this name already saved..." */
    kMetStrFreqNewName = 943,      /*!< "There is a FreQ with this name already saved..." */
    kMetStrFreqNoName = 944,       /*!< "You must name your FreQ." */
    kMetStrDiscardRemix = 945,     /*!< "Are you sure you want to discard your Remix?" */
    kMetStrDiscardRemixChanges = 946, /*!< "Are you sure you want to discard your changes?" */
    kMetStrRemixDelAsk = 947,         /*!< "Are you sure you want to delete this Remix?" */
    kMetStrRemixCopyAsk = 948,        /*!< "Are you sure you want to copy this Remix..." */
    kMetStrNoRemixOnCard = 949,       /*!< "There are no Remixes on the memory card (PS2)..." */
    kMetStrNoFreqOnCard = 950,        /*!< "There are no FreQ campaigns on the memory card..." */
    kMetStrRemixDel1 = 951,           /*!< "Deleting your Remix from memory card (PS2)..." */
    kMetStrRemixDel2 = 952,           /*!< ". Do not remove your memory card (PS2)." */
    kMetStrRemixCopy1 = 953,          /*!< "Copying your Remix to memory card (PS2)..." */
    kMetStrRemixCopy2 = 954,          /*!< "Do not remove your memory card (PS2)." */
    kMetStrMemRemixDupe = 955,        /*!< "Are you sure you want to overwrite your saved Remix:" */
    kMetStrMemRemix2many = 956,       /*!< "Save Failed. No more than %d remixes can be saved..." */
    kMetStrRemixLoad = 957,           /*!< "Loading Remix from memory card (PS2)..." */
    kMetStrCustomLoad = 958,          /*!< "Loading Custom Song from memory card (PS2)..." */
    kMetStrMcrfRemix = 959,           /*!< "REMIXES" */
    kMetStrMcrfFreq = 960,            /*!< "FREQS" */
    kMetStrMcrfRemixdata = 961,       /*!< "REMIX DATA" */
    kMetStrMcrfFreqdata = 962,        /*!< "FREQ DATA" */
    kMetStrMcrfBorn = 963,            /*!< "Born:" */
    kMetStrFactListLoad = 964,        /*!< "Loading Remix List from DISC. Do not remove DISC." */
    kMetStrFactRemixLoad = 965,       /*!< "Loading Remix from DISC. Do not remove DISC." */
    kMetStrFactCustomLoad = 966,      /*!< "Loading Custom Song from DISC. Do not remove DISC." */
    kMetStrRemixListLoad = 967,       /*!< "Loading Remix List from memory card (PS2)..." */
    kMetStrMcLoadFail = 968,          /*!< "Could not load data from memory card (PS2)..." */
    kMetStrMcLoadFailNoCard = 969,    /*!< "Load failed. No memory card (PS2) detected..." */
    kMetStrSaveRemixCommand = 970,    /*!< "Enter a title to save your Remix in slot %s." */
    kMetStrWarnRemixNoSpace = 971,  /*!< "There may be insufficient space to save Remix data..." */
    kMetStrMultRemixNoCard = 972,   /*!< "memory cards (PS2) were not detected in all slots..." */
    kMetStrMultRemixNoSpace = 973,  /*!< "Some memory cards (PS2) have insufficient space..." */
    kMetStrMemCopy12 = 974,         /*!< "Copying data from memory card (PS2) in slot %s..." */
    kMetStrCopyFailNocard = 975,    /*!< "Copy failed. No memory card (PS2) was detected..." */
    kMetStrCopyFailNospace = 976,   /*!< "Copy failed. Insufficient space on memory card..." */
    kMetStrCopyFailFormat = 977,    /*!< "Copy failed. The memory card (PS2) is not formatted..." */
    kMetStrCopyFailGeneral = 978,   /*!< "Copy failed." */
    kMetStrSaveTitle = 979,         /*!< "SAVING" */
    kMetStrCopyTitle = 980,         /*!< "COPYING" */
    kMetStrTMclCard = 981,          /*!< "MEMORY CARD slot SELECT" */
    kMetStrTMemDelType = 982,       /*!< "MEMORY CARD SLOT %s" */
    kMetStrTMemLoadRemix = 983,     /*!< "MEMORY CARD SLOT %s: LOAD REMIX" */
    kMetStrTMemLoadCustom = 984,    /*!< "MEMORY CARD SLOT %s: LOAD CUSTOM" */
    kMetStrTFactLoadCustom = 985,   /*!< "FACTORY: LOAD CUSTOM" */
    kMetStrTFactLoadRemix = 986,    /*!< "FACTORY: LOAD REMIX" */
    kMetStrHMclCard = 987,          /*!< "<FC> c <F1> refresh" */
    kMetStrHMcrfRemix = 988,        /*!< "delete or copy your remixes" */
    kMetStrHMcrfFreq = 989,         /*!< "delete or copy your freQs" */
    kMetStrHDelFreq = 990,          /*!< "<FC> a <F1> - delete a freQ, <FC> c <F1> - copy..." */
    kMetStrHMemDelRemix = 991,      /*!< "<FC> a <F1> - delete a remix, <FC> c <F1> - copy..." */
    kMetStrHRemixLoadOpt = 992,     /*!< "<FC> d <F2>LOAD <FC> b <F2>BACK" */
    kMetStrHDelOpt = 993,           /*!< "<FC> a <F2>DELETE <FC> b <F2>BACK" */
    kMetStrHMcOpt = 994,            /*!< "<FC> d <F2>LOAD <FC> b <F2>BACK" */
    kMetStrHMemCardPickTitle = 995, /*!< "<FC> d <F2>LOAD <FC> b <F2>BACK" */
    kMetStrMsgERROR = 996,          /*!< "ERROR" */
    kMetStrMsgFREQUENCY = 997,      /*!< "FREQUENCY" */
    kMetStrMsgWARNING = 998,        /*!< "WARNING" */
    kMetStrMsgSETTINGS = 999,       /*!< "SETTINGS" */
    kMetStrMsgFORMAT = 1000,        /*!< "FORMAT" */
    kMetStrMsgCONFIRM = 1001,       /*!< "CONFIRM" */
    kMetStrMsgCOPY = 1002,          /*!< "COPY" */
    kMetStrMsgDELETE = 1003,        /*!< "DELETE" */
    kMetStrMsgOK = 1004,            /*!< "OK" */
    kMetStrMsgRETRY = 1005,         /*!< "RETRY" */
    kMetStrMsgCONTINUE = 1006,      /*!< "CONTINUE" */
    kMetStrMsgYES = 1007,           /*!< "YES" */
    kMetStrMsgNO = 1008,            /*!< "NO" */
    kMetStrMsgBACK = 1009,          /*!< "BACK" */
    kMetStrMsgCANCEL = 1010,        /*!< "CANCEL" */
    kMetStrMsgLOADING = 1011,       /*!< "LOADING" */

    // MetStrDemo
    kMetStrDEMOGameSelectButton0Text = 1100,  /*!< "TUTORIAL" */
    kMetStrDEMOGameSelectButton1Text = 1101,  /*!< "SONG 1:NORMAL" */
    kMetStrDEMOGameSelectButton2Text = 1102,  /*!< "SONG 2:NORMAL" */
    kMetStrDEMOGameSelectButton3Text = 1103,  /*!< "SONG 1:ADVANCED" */
    kMetStrDEMOGameSelectButton4Text = 1104,  /*!< "SONG 2:ADVANCED" */
    kMetStrDEMORemixSelectButton0Text = 1105, /*!< "TUTORIAL" */
    kMetStrDEMORemixSelectButton1Text = 1106, /*!< "SONG 1:REMIX" */
    kMetStrDEMORemixSelectButton2Text = 1107, /*!< "SONG 2:REMIX" */
    kMetStrDEMORemixSelectButton3Text = 1108, /*!< "SONG 3:REMIX" */
    kMetStrDEMORemixSelectButton4Text = 1109, /*!< "SONG 4:REMIX" */
    kMetStrDEMOLevelSelection1 = 1110,        /*!< "nodoubt" */
    kMetStrDEMOLevelSelection2 = 1111,        /*!< "oakenf" */
    kMetStrDEMOLevelSelection3 = 1112,        /*!< "nodoubt" */
    kMetStrDEMOLevelSelection4 = 1113,        /*!< "oakenf" */
    kMetStrDEMOLevelSelectionGame = 1114,     /*!< "tutorial" */
    kMetStrDEMOLevelSelectionRemix = 1115,    /*!< "tutorialrmx" */
    kMetStrTDEMOGameTitleText = 1116,         /*!< "DEMO GAME: SELECT SONG" */
    kMetStrTDEMORemixTitleText = 1117,        /*!< "DEMO REMIX: SELECT SONG" */
    kMetStrHDEMOGameSelectButton1 = 1118,     /*!< "beat the first normal level" */
    kMetStrHDEMOGameSelectButton2 = 1119,     /*!< "beat the second normal level" */
    kMetStrHDEMOGameSelectButton3 = 1120,     /*!< "beat the first advanced level" */
    kMetStrHDEMOGameSelectButton4 = 1121,     /*!< "beat the second advanced level" */
    kMetStrHDEMORemixSelectButton1 = 1122,    /*!< "remix the first song" */
    kMetStrHDEMORemixSelectButton2 = 1123,    /*!< "remix the second song" */
    kMetStrHDEMORemixSelectButton3 = 1124,    /*!< "remix the third song" */
    kMetStrHDEMORemixSelectButton4 = 1125,    /*!< "remix the fourth song" */

    // MetStrInGame
    kMetStrIngStart = 1200,       /*!< "START" */
    kMetStrIngFinal = 1201,       /*!< "FINAL\nSECTION" */
    kMetStrIngFinish = 1202,      /*!< "FINISH" */
    kMetStrIngAutocatcher = 1203, /*!< "AUTOCATCHER" */
    kMetStrIngBumper = 1204,      /*!< "BUMPER" */
    kMetStrIngCrippler = 1205,    /*!< "CRIPPLER" */
    kMetStrIngFreestyler = 1206,  /*!< "FREESTYLER" */
    kMetStrIngNeutralizer = 1207, /*!< "NEUTRALIZER" */
    kMetStrIngVolume = 1208,      /*!< "Volume" */
    kMetStrIngWah = 1209,         /*!< "Wah" */
    kMetStrIngStutter = 1210,     /*!< "Stutter" */
    kMetStrIngEcho = 1211,        /*!< "Echo" */
    kMetStrIngFlange = 1212,      /*!< "Flange" */
    kMetStrIngChorus = 1213,      /*!< "Chorus" */
    kMetStrIngGuides = 1214,      /*!< "Guides" */
    kMetStrIngMultiplier = 1215,  /*!< "MULTIPLIER" */
    kMetStrIngMult = 1216,        /*!< "x%d" */
    kMetStrIngCongrat1 = 1217,    /*!< "CONGRATULATIONS!\n\nYOU ARE NOW A\nTRUE FREQ" */
    kMetStrIngCongrat2 = 1218,    /*!< "CONGRATULATIONS!\n\nYOU ARE NOW A\nSUPER FREQ!" */
    kMetStrIngCongrat3 = 1219,    /*!< "CONGRATULATIONS!\n\nYOU ARE NOW A\nMEGA FREQ!!" */
    kMetStrIngCongratDef = 1220,  /*!< "Yup" */
    kMetStrIngWinMsg1 = 1221,     /*!< "TEAM FREQUENCY\nBELIEVES THERE IS\nNO GREATER HIGH..." */
    kMetStrIngWinMsg2 = 1222,     /*!< "WE HOPE YOU ENJOYED\nSHAKING YOUR BOOTY..." */
    kMetStrIngStartPress = 1223,  /*!< "Press the START button to exit" */
    kMetStrIngDRUMS = 1224,       /*!< "DRUMS" */
    kMetStrIngBASS = 1225,        /*!< "BASS" */
    kMetStrIngSYNTH = 1226,       /*!< "SYNTH" */
    kMetStrIngGUITAR = 1227,      /*!< "GUITAR" */
    kMetStrIngVOCAL = 1228,       /*!< "VOCAL" */
    kMetStrIngFX = 1229,          /*!< "FX" */
    kMetStrIngAXE = 1230,         /*!< "AXE" */
    kMetStrIngSCRATCH = 1231,     /*!< "SCRATCH" */
    kMetStrIngJukePress = 1232,   /*!< "Jukebox Mode\nPress the START button to quit" */
    kMetStrIngDemoPress = 1233,   /*!< "DEMO\n\nPress any button to exit" */
    kMetStrIngFreePress = 1234,   /*!< "FREESTYLE\n\nPress the START button to exit" */
    kMetStrIngYOU = 1235,         /*!< "YOU" */
    kMetStrIngWIN = 1236,         /*!< "WIN" */
    kMetStrIngLOSE = 1237,        /*!< "LOSE" */
    kMetStrIngGAME = 1238,        /*!< "GAME" */
    kMetStrIngOVER = 1239,        /*!< "OVER" */
    kMetStrIngCaptured = 1240,    /*!< "\nCAPTURED" */
    kMetStrIngDeployed = 1241,    /*!< "\nDEPLOYED" */
    kMetStrIngBumped = 1242,      /*!< "YOU GOT\nBUMPED!" */
    kMetStrIngAutocatcherFail = 1243, /*!< "AUTOCATCHER FAILED\nUSE ON\nFREE TRACK" */
    kMetStrIngCripplerFail = 1244,    /*!< "CRIPPLER FAILED\nUSE ON\nOTHER PLAYER" */
    kMetStrIngNeutralizerFail = 1245, /*!< "NEUTRALIZER FAILED\nUSE ON\nCAPTURED TRACK" */
    kMetStrIngBumperFail = 1246,      /*!< "BUMPER FAILED\nUSE ON\nOTHER PLAYER" */
    kMetStrIngFreestylerFail = 1247,  /*!< "FREESTYLER FAILED\nUSE ON\nFREESTYLE TRACK" */
    kMetStrIngAdvance = 1248,         /*!< "ADVANCE TO\nNEXT SECTION" */
    kMetStrIngRepeat = 1249,          /*!< "REPEAT\nSECTION" */
    kMetStrIngLoopOn = 1250,          /*!< "LOOP ON" */
    kMetStrIngLoopOff = 1251,         /*!< "LOOP OFF" */
    kMetStrIngSelPress = 1252,        /*!< "Press the SELECT button to edit" */
    kMetStrIngBarErase = 1253,        /*!< "BAR ERASED" */
    kMetStrIngTrackErase = 1254,      /*!< "TRACK ERASED" */
    kMetStrIngRotate = 1255,          /*!< "ROTATE TO\nNEW TRACK" */
    kMetStrIngNeutralized = 1256,     /*!< "NEUTRALIZED!\n%d POINTS" */
    kMetStrIngCtrlPan = 1257,         /*!< "CONTROLLER" */
};
